menu:
  Archives: /archives
#footer_links/links
links:
- name: 카지노사이트
  link: https://choegocasino.com/

#- name: Kieran
#  link: http://go.kieran.top/
#- name: Name
#  link: http://domain.com/
color: "#339999"
widgets:
- search
- recent_posts
- category
- tagcloud

excerpt_link: Read More ›

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

google_analytics:
